version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: openagent-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openagent
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: openagent-postgres
