[project]
name = "openagent"
version = "2.0.0"
description = "OpenAgent is a framework for building AI applications leveraging the power of blockchains and RSS3 Network."
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "anthropic>=0.42.0",
    "fastapi>=0.115.6",
    "google-generativeai>=0.8.3",
    "loguru",
    "ollama>=0.4.5",
    "openai>=1.59.6",
    "phidata>=2.7.7",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.34.0",
    "yfinance>=0.2.51",
]

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.1"
