[project]
name = "openagent"
version = "2.0.0"
description = "OpenAgent is a framework for building AI applications leveraging the power of blockchains and RSS3 Network."
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "anthropic>=0.42.0",
    "fastapi>=0.115.6",
    "google-generativeai>=0.8.3",
    "loguru",
    "ollama>=0.4.5",
    "openai>=1.59.6",
    "phidata>=2.7.7",
    "python-dotenv>=1.0.1",
    "sqlalchemy-orm>=1.2.10",
    "uvicorn>=0.34.0",
    "yfinance>=0.2.51",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "atlas-provider-sqlalchemy (>=0.2.4,<0.3.0)",
    "alembic (>=1.14.0,<2.0.0)",
    "eth-account (>=0.13.4,<0.14.0)",
    "web3 (>=7.7.0,<8.0.0)",
    "redis (>=5.2.1,<6.0.0)",
]

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.1"
