name: Lint and Format

on:
  push:
    branches:
      - oa
  pull_request:
    branches:
      - oa

jobs:
  lint-and-format:
    name: lint-and-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Run Ruff Check
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --fix"
          version-file: "pyproject.toml"

      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          version-file: "pyproject.toml"
